### ISSUE TITLE
Внести изменения (часть 1)

### ISSUE THREAD

**Issue by MaratKhaid** [sima-land/ui-quarks#73]
В иконках требовалось много изменений. Решили разделить изменения на несколько задач. Первая партия изменений:

**16х16
Добавить:**

 Stroked/Variation

 Filled/Check

 Filled/GeoArrow

 Filled/Feedback

 Colorful/DeliveryPost

 Colorful/DeliveryDPD

 Colorful/DeliveryDalli

 Colorful/DeliveryBoxberry

 Colorful/DeliveryPickPoint

 Colorful/Delivery5Post

 Colorful/DeliverySDEK

 Colorful/DeliveryOzon

 Colorful/DeliverySima

 Colorful/DeliverySberLogistic

 Colorful/DeliveryYandex

 Colorful/DeliveryGalamart

 Colorful/DeliveryAptekaPlus

 Colorful/DeliveryDelovieLinii

 Colorful/DeliveryOzonSima

 Colorful/DeliveryWildberriesSima

 Colorful/DeliveryAvitoSima

**Переименовать:**

 Stroked/Arrows/ExpandRight на Stroked/ArrowExpandRight

 Stroked/Arrows/ExpandLeft на Stroked/ArrowExpandLeft

 Stroked/Arrows/ExpandUp на Stroked/ArrowExpandUp

 Stroked/Arrows/ExpandDown на Stroked/ArrowExpandDown

 Stroked/Arrows/UpAndDown на Stroked/ArrowUpAndDown

 Stroked/Arrows/Right на Stroked/ArrowRight

 Stroked/Arrows/Left на Stroked/ArrowLeft

 Stroked/Arrows/Up на Stroked/ArrowUp

 Stroked/Arrows/Down на Stroked/ArrowDown

 Stroked/Arrows/TurnRight на Stroked/ArrowTurnRight

 Stroked/Arrows/TurnLeft на Stroked/ArrowTurnLeft

 Stroked/Arrows/DownSquare на Stroked/ArrowDownSquare

**24х24
Добавить:**

 Stroked/Unlock

 Stroked/ArrowExpandRight

 Stroked/ArrowExpandLeft

 Stroked/Moon

 Stroked/System

 Stroked/Sun

 Stroked/ Certificate

 Stroked/18+

 Stroked/ChestnyZnak

 Stroked/Contacts

 Stroked/Playicon

 Stroked/Briefcase

 Stroked/PercentageSign

 Stroked/Comment

 Stroked/Share

 Colorful/LogoVisaDarkMode

 Colorful/LogoVsegdaDaDarkMode

**Переименовать:**

Stroked/Bag2 на Stroked/Bag

 Stroked/Arrows/Down на Stroked/ArrowExpandDown

 Stroked/Arrows/Up на Stroked/ArrowExpandUp

 Stroked/Camera2 на Stroked/Camera

 Stroked/SpeakerOn на Stroked/Speaker

 Stroked/MicrophoneOn на Stroked/Microphone

**Перевыгрузить**

 Filled/SocialVK

 Colorful/LogoYandexSplit

**32х32
Добавить:**

 Colorful/DeliveryPost

 Colorful/DeliveryBoxberry

 Colorful/DeliveryDPD

 Colorful/DeliverySDEK

 Colorful/DeliveryPickPoint

 Colorful/Delivery5Post

 Colorful/DeliveryOzon

 Colorful/DeliverySima

 Colorful/DeliverySberLogistic

 Colorful/DeliveryYandex

 Colorful/DeliveryAptekaPlus

 Colorful/DeliveryGalamart

 Colorful/DeliveryDelovieLinii

**40х40
Добавить:**

 Stroked/PlayRound

 Filled/Button360

**Comment by krutoo** [comment]
по именованию предлагаю соблюдать принцип "имя должно отражать то что нарисовано в кионке а не то где она будет использоваться" поэтому также предлагаю: 

- приставку Delivery у логотипов доставок заменить на Logo чтобы проще называлось (там как раз большая часть не имеет отношения напрямую к доставке а является чисто логотипом компании в круге) 

- Button360 и Round360 переименовать на Viewing360 и Viewing360Perspective как вариант так как иконки сейчас по сути одно и тоже означают а названия сбивают с толку

- иконки деловых линий переименовать на что-то типа Dellin в соответствии с тем как у них на сайте и в соцсетях (https://www.dellin.ru/)

- приставку Dropdown у иконок которые для выпадающего меню убрать так как они сейчас выглядят так что могут использоваться и вне этого выпадающего меню

- приставку Social убрать по той же причине - это сейчас просто логотипы в кругах
